version: "3"

services:

  app:

      build: .

      volumes:
        - .:/app
      ports:
        - "8080:8080"

  worker:

    build: .
    hostname: celery-host
    command: "celery -A tasks worker --loglevel=INFO"
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - redis

  flower:
    image: mher/flower
    hostname: flower-host
    environment:
     - CELERY_BROKER_URL=redis://redis:6379
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    links:
      - worker
    depends_on:
      - worker
  
  redis:
    image: redis:latest
    hostname: redis    